default_platform(:ios)

platform :ios do
  desc "Build an unsigned xcarchive"
  lane :build_unsigned do
    gym(
      configuration: "Release",
      project: "StudyOn.xcodeproj",
      output_directory: "./output/archive",
      archive_path: "./output/archive/StudyOn.xcarchive",
      export_method: "ad-hoc",  # This is required, but won't affect since we're not exporting an IPA
      skip_codesigning: true,
      skip_package_ipa: true,
      export_options: {
        compileBitcode: false,
        method: "ad-hoc",
        signingStyle: "manual",
        provisioningProfiles: {},
        signingCertificate: "",
        teamID: "",
        uploadSymbols: false,
        stripSwiftSymbols: true,
        thinning: "<none>",
        iCloudContainerEnvironment: "Production"
      }
    )
  end

  desc "Create unsigned IPA from xarchive"
  lane :create_unsigned_ipa do
    archive_path = "./output/archive/StudyOn.xcarchive"
    ipa_output_path = "./output/archive"
    sh "mkdir -p #{ipa_output_path}"
    sh "cp -R #{archive_path}/Products/Applications/StudyOn.app #{ipa_output_path}/Payload/StudyOn.app"
    sh "cd #{ipa_output_path} && zip -r StudyOn.ipa Payload"
  end
end
