default_platform(:ios)

platform :ios do
  desc "Build an unsigned IPA"
  lane :build_unsigned do
    gym(
      output_directory: "./output/ipa",  # Ensure this path matches the CircleCI config
      output_name: "MyApp.ipa",
      export_method: "development",  # or "ad-hoc"
      export_options: {
        compileBitcode: false,
        method: "development",  # or "ad-hoc"
        signingStyle: "manual",
        provisioningProfiles: {}
      },
      export_xcargs: "-allowProvisioningUpdates"
    )
  end
end
